In [2]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import scipy

##### Задача 1.1

In [34]:
data1 = pd.read_csv('data-csv/sleep75.csv')
data1.shape

(706, 34)

In [53]:
# Создаем спецификацию модели через формулу
mod1 =smf.ols(formula='sleep~totwrk+age+south+male+smsa+yngkid+marr+union', data=data1)
#Подгоняем модель
Sleep_eq1 = mod1.fit()

In [54]:
# отчет представляет собой набор из трёх таблиц(нумерация начинается с нулевой). 
# Нас интересуте вторая таблица(под индексом 1)
Sleep_eq1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sleep   R-squared:                       0.131
Model:                            OLS   Adj. R-squared:                  0.121
Method:                 Least Squares   F-statistic:                     13.18
Date:                Tue, 07 Mar 2023   Prob (F-statistic):           8.33e-18
Time:                        22:00:18   Log-Likelihood:                -5255.9
No. Observations:                 706   AIC:                         1.053e+04
Df Residuals:                     697   BIC:                         1.057e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3446.8303     81.840     42.117      0.000    3286.148    3607.513
totwrk        -0.1691      0.018     -9.358      0.000      -0.205      -0.134
age            2.7145      1.472      1.844      0.066      -0.176       5.605
south        102.2718     41.925      2.439      0.015      19.957     184.586
male          87.1081     35.173      2.477      0.014      18.050     156.166
smsa         -54.1877     33.193     -1.632      0.103    -119.359      10.983
yngkid       -13.0513     50.459     -0.259      0.796    -112.121      86.019
marr          31.3604     42.263      0.742      0.458     -51.618     114.339
union         11.8657     38.186      0.311      0.756     -63.107      86.839
==============================================================================
Omnibus:                       61.853   Durbin-Watson:                   1.946
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              166.463
Skew:                          -0.443   Prob(JB):                     7.13e-37
Kurtosis:                       5.208   Cond. No.                     1.28e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.28e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [55]:
# Отобразим интересующую нас таблицу
table = Sleep_eq1.summary().tables[1]
table

In [56]:
# Извлечь данные из данной таблицы можно вручную (Ctrl - C, Ctrl - V) и получить строку, чтобу преобразовать её в DataFrame
# А можно сохранить в виде html файла и уже его преобразовать в DataFrame
df = pd.read_html(Sleep_eq1.summary().tables[1].as_html(), header=0, index_col=0)[0] # Эту строку запоминать не нужно
df

                coef  std err       t  P>|t|    [0.025    0.975]
Intercept  3446.8303   81.840  42.117  0.000  3286.148  3607.513
totwrk       -0.1691    0.018  -9.358  0.000    -0.205    -0.134
age           2.7145    1.472   1.844  0.066    -0.176     5.605
south       102.2718   41.925   2.439  0.015    19.957   184.586
male         87.1081   35.173   2.477  0.014    18.050   156.166
smsa        -54.1877   33.193  -1.632  0.103  -119.359    10.983
yngkid      -13.0513   50.459  -0.259  0.796  -112.121    86.019
marr         31.3604   42.263   0.742  0.458   -51.618   114.339
union        11.8657   38.186   0.311  0.756   -63.107    86.839

In [57]:
# Дополним DataFrame признаком t-values
df['tvalues']  = df['coef']/df['std err']
df

                coef  std err       t  P>|t|    [0.025    0.975]    tvalues
Intercept  3446.8303   81.840  42.117  0.000  3286.148  3607.513  42.116695
totwrk       -0.1691    0.018  -9.358  0.000    -0.205    -0.134  -9.394444
age           2.7145    1.472   1.844  0.066    -0.176     5.605   1.844090
south       102.2718   41.925   2.439  0.015    19.957   184.586   2.439399
male         87.1081   35.173   2.477  0.014    18.050   156.166   2.476562
smsa        -54.1877   33.193  -1.632  0.103  -119.359    10.983  -1.632504
yngkid      -13.0513   50.459  -0.259  0.796  -112.121    86.019  -0.258652
marr         31.3604   42.263   0.742  0.458   -51.618   114.339   0.742030
union        11.8657   38.186   0.311  0.756   -63.107    86.839   0.310734

In [58]:
# Сравним в полученными значениями с помощью регрессионной модели
# t-значение для коэффициентов при регрессорах с округлением
Sleep_eq1.tvalues.round(3)

Intercept    42.117
totwrk       -9.358
age           1.844
south         2.439
male          2.477
smsa         -1.632
yngkid       -0.259
marr          0.742
union         0.311
dtype: float64

1.2

In [29]:
# Создаем спецификацию модели через формулу
mod2 = smf.ols(formula=' sleep~totwrk+age+south+male+smsa+yngkid+marr+union+np.log(hrwage)', data=data1)
#Подгоняем модель
Sleep_eq2 = mod2.fit()

In [31]:
# отчет
Sleep_eq2.summary().tables[1]

### Проверка значимости коэффциентов регрессии Sleep_eq2

### Тестируем гипотезу $H_0:\beta_{j}=0$ VS $H_1:\beta_{j}\ne 0$ 

#### В отчете печатается следующая информация

#### в столбце $coef$: $\hat{\beta}_{j}$

#### в столбце $std \quad err$: $s.e.(\beta_{j})$

#### в столбце $t$:  $t$-value, $\displaystyle t=\frac{\hat{\beta_j}}{s.e.(\beta_j)}$

#### в столбце P>|t|: $p$-value

In [67]:
alpha = 0.1 # уровень значимости
print('Уровень значимости alpha: ', alpha)
DF = int(Sleep_eq2.df_resid) # число степеней свободы 
t_crit = scipy.stats.t.ppf(1-alpha/2, DF)
print('Критическое значение t_crit: ', t_crit.round(3))

Уровень значимости alpha:  0.1
Критическое значение t_crit:  1.648

In [59]:
df['znachimosty'] = df.apply(lambda x : 'znachim' if np.abs(x['tvalues']) > t_crit else 'ne znachim', axis = 1 )
df

,coef,std err,t,P>|t|,[0.025,0.975],tvalues,znachimosty
Intercept,3446.8303,81.840,42.117,0.000,3286.148,3607.513,42.116695,znachim
totwrk,-0.1691,0.018,-9.358,0.000,-0.205,-0.134,-9.394444,znachim
age,2.7145,1.472,1.844,0.066,-0.176,5.605,1.844090,znachim
south,102.2718,41.925,2.439,0.015,19.957,184.586,2.439399,znachim
male,87.1081,35.173,2.477,0.014,18.050,156.166,2.476562,znachim
smsa,-54.1877,33.193,-1.632,0.103,-119.359,10.983,-1.632504,ne znachim
yngkid,-13.0513,50.459,-0.259,0.796,-112.121,86.019,-0.258652,ne znachim
marr,31.3604,42.263,0.742,0.458,-51.618,114.339,0.742030,ne znachim
union,11.8657,38.186,0.311,0.756,-63.107,86.839,0.310734,ne znachim

##### Задача 2.1

In [61]:
data2 = pd.read_csv('data-csv/Labour.csv')
data2.shape

(569, 4)

In [62]:
# Создаем спецификацию модели через формулу
mod3 = smf.ols(formula='np.log(output)~np.log(capital)+np.log(labour)', data=data2)
#Подгоняем модель
Output_eq1 = mod3.fit()

In [63]:
Output_eq1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:         np.log(output)   R-squared:                       0.838
Model:                            OLS   Adj. R-squared:                  0.837
Method:                 Least Squares   F-statistic:                     1462.
Date:                Tue, 07 Mar 2023   Prob (F-statistic):          2.64e-224
Time:                        22:01:11   Log-Likelihood:                -385.95
No. Observations:                 569   AIC:                             777.9
Df Residuals:                     566   BIC:                             790.9
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -1.7115      0.097    -17.697      0.000      -1.901      -1.522
np.log(capital)     0.2076      0.017     12.077      0.000       0.174       0.241
np.log(labour)      0.7148      0.023     30.890      0.000       0.669       0.760
==============================================================================
Omnibus:                      259.475   Durbin-Watson:                   1.963
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2677.293
Skew:                           1.734   Prob(JB):                         0.00
Kurtosis:                      13.045   Cond. No.                         24.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [66]:
alpha = 0.01
print('Уровень значимости alpha: ', alpha)
DF = int(Output_eq1.df_resid)
t_crit = scipy.stats.t.ppf(1-alpha/2, DF)
print('Критическое значение t_crit: ', t_crit.round(3))

Уровень значимости alpha:  0.01
Критическое значение t_crit:  2.585

### Тестируем гипотезу $H_0:\beta_{capital}=0.5$ VS $H_0:\beta_{capital}\ne 0.5$

### Петатается $\hat{\beta}_{capital}$, $s.e.(\beta_{capital})$, $\displaystyle t=\frac{\hat{\beta}-0.5}{s.e.(\beta)}$

In [65]:
# формулируем гипотезу
hypotheses = 'np.log(capital)=0.5' # Запись означает: коэффициент при регрессоре log(capital) равен 0.5
# проверяем гипотезу
Output_eq1.t_test(hypotheses)

<class 'statsmodels.stats.contrast.ContrastResults'>
                             Test for Constraints
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
c0             0.2076      0.017    -17.014      0.000       0.174       0.241
==============================================================================

### ВЫВОД: Так как $|t-value| > t-crit$ => отвергаем $H_0$ => коэффициент при регрессоре $log(capital)$ значимо отличается от числа 0.5